

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 8.x'
  inputs:
    version: 8.x

- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 9.x'
  inputs:
    version: 9.x

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '-c $(BuildConfiguration)'
  displayName: 'build projects'

