

trigger:
- firebase-demo

pool:
  vmImage: 'windows-2019'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CmdLine@2
  inputs:
    script: 'npm install -g firebase-tools'
    workingDirectory: '$(Agent.ToolsDirectory)'
  displayName: 'install firebase tools'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/ElCamino.DocFx.WebAppRefresh.Sample.sln'
    arguments: '-c $(BuildConfiguration)'
  displayName: 'build web project'

- task: CmdLine@2
  inputs:
    script: 'firebase deploy --token "$(FIREBASE_TOKEN)" -m "$(Build.BuildNumber)"'
    workingDirectory: '$(System.DefaultWorkingDirectory)\\sample\\ElCamino.DocFx.WebAppRefresh.Sample\\'
  displayName: 'firebase publish -m "$(Build.BuildNumber)"'
